import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Choice from "../components/top/Choice";
import TopOffice from "../components/top/TopOffice";
import TopCompany from "../components/top/TopCompany";
import TopData from "../components/top/TopData";
import Allow from "../components/animetion/Allow";
import TopEntry from "../components/top/TopEntry";
import Fv from "../components/animetion/Fv";
import { useEffect } from "react";
import { type } from "os";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // const load = () => {
  //   if (typeof window === "object") {
  //     window.location.reload();
  //   }
  // };
  // load();

  // useEffect(() => {
  //   location.reload();
  // }, []);
  return (
    <>
      <Head>
        <title>KDDI Web Comunnications オフィス紹介サイト</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="base-color">
        <article>
          <h1 className="relative">
            <div className="w-full h-full">
              <Fv />
              <div className="max-md:hidden">
                <Allow />
              </div>
            </div>
          </h1>
          <section className="mt-[280px]  w-2/5 mx-auto max-md:w-[80%] max-md:mt-[100px]">
            <div className="p-8 read-bgc">
              <h2 className="h2-font text-center max-md:text-xl max-md:font-bold">
                ミライのカタチをつくる
              </h2>
              <p className="mt-16 mx-auto w-4/5">
                私たちが繋がっているイマには、多くの選択肢があり、ワークライフを自らがデザインすることで、大切な人たちの時間、趣味の時間、あるいは自分の成長のために時間を使うことができます。様々な選択肢があなたのミライを広げていきます。
              </p>
            </div>
          </section>
          <section>
            <h2 className="h2-font text-center mt-[280px] max-md:text-xl max-md:mt-[100px]">
              選択肢を増やす選択を
            </h2>
            <Choice />
          </section>

          <section>
            <h2 className="h2-font text-center">Office</h2>
            <TopOffice />
          </section>
          <TopCompany />
          <TopData />
          <TopEntry />
        </article>
      </main>
      <Footer />
    </>
  );
}
