import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Choice from "../components/top/Choice";
import TopOffice from "../components/top/TopOffice";
import TopCompany from "../components/top/TopCompany";
import TopData from "../components/top/TopData";
import Animetion from "../components/animetion/Animetion";
import Allow from "../components/animetion/Allow";
import TopEntry from "../components/top/TopEntry";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>KDDI Web Comunnications オフィス紹介サイト</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="base-color ">
        <Header />
        <article className="overflow-hidden">
          <h1 className="relative">
            <div className="h1-font max-md:text-xl z-10">
              繋がるイマ
              <br />
              広がるミライ
            </div>
            <div className="mainbg  max-md:h-[800px]">
              <Animetion />
              <Allow />
            </div>
          </h1>
          <section className=" m-[280px] relative  w-2/5 mx-auto max-md:w-3/4">
            <div className="p-8 absolute max-md:top-[-100px] read-bgc">
              <h2 className="h2-font text-center max-md:text-xl max-md:font-bold">
                ミライのカタチをつくる
              </h2>
              <p className="mt-16 mx-auto w-4/5">
                私たちが繋がっているイマには、多くの選択肢があり、ワークライフを自らがデザインすることで、大切な人たちの時間、趣味の時間、あるいは自分の成長のために時間を使うことができます。様々な選択肢があなたのミライを広げていきます。
              </p>
            </div>
          </section>
          <section>
            <h2 className="h2-font text-center mt-[780px] max-md:text-xl">
              選択肢を増やす選択を
            </h2>
            <Choice />
          </section>

          <section>
            <h2 className="h2-font text-center">Office</h2>
            <TopOffice />
          </section>
          <TopCompany />
          <TopData />
          <TopEntry />
          <Footer />
        </article>
      </main>
    </>
  );
}
