import React from "react";
import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Concept from "../components/office/Concept";
import OffSlider from "../components/office/OffSlider";
import Lounge from "../components/office/Lounge";
import Interview from "../components/office/Interview";

function Office() {
  return (
    <div>
      <Head>
        <title>KDDI Web Comunnications オフィス紹介サイト</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="base-color">
        <Header />
        <h1>
          <div className="off-main w-full max-md:bg-contain max-md:-mt-3 max-md:h-[155px] max-md:bg-bottom max-md:bg-no-repeat"></div>
        </h1>
        <Concept />
        <OffSlider />
        <Lounge />
        <Interview />

        <Footer />
      </main>
    </div>
  );
}

export default Office;
