import React from "react";
import Image from "next/image";
import Head from "next/head";
import Close from "../components/atoms/Close";

function time() {
  const data = [
    {
      img: "/fullflex.png",
      h2: "働く時間の選択",
      text: [
        {
          h3: "フルフレックス",
          p: "コアタイムを設けないフルフレックスタイム制およびコアタイムありのフレックスタイム制を導入しています。極端に言えば1日1時間だけ働く日もあれば、10時間働く日があってもOKです。1ヶ月の労働時間が基準を満たしていれば問題ありません。例えば、経理部のように月初、月半ば、月末で業務量が異なる部署や、子育てをしている社員に喜ばれています。また、テレワークと併用することができるので、勤務時間を日によって変えながら自宅でテレワークすることができます。時短勤務でフルフレックス制度を利用することも可能なので、より自由度の高い働き方が可能です。",
        },
        {
          h3: "時短勤務",
          p: "子育てをしながら働く社員を中心に、6時間勤務などで働く社員がいます。時短勤務とフルフレックスを組み合わせ、その日の都合に合わせ工夫して使用している社員もいます。",
        },
        {
          h3: "選べる出社時間（フレックス勤務ではない部署対象）",
          p: "定刻勤務の中でも、①9:00－17:30 / ②9:30-18:00 / ③10:00-18:30 の3つ勤務パターンからその日ごとに自由に選び出勤することができます。",
        },
        {
          h3: "時差出勤（フレックス勤務ではない部署対象）",
          p: "定刻勤務の3つの勤務パターン以外にも申請すれば、①8:00-16:30 / ②11:00-19:30 / ③12:00-20:30という勤務も可能です。出社時間に柔軟性を持たせることで、業務効率の最適化や、時間管理の向上を図っています。",
        },
        {
          h3: "7.5h勤務",
          p: "2017年4月より、それまで8時間だった勤務時間を見直し、7.5時間勤務となりました。社員ひとりひとりがタイムマネジメントを行い、短い時間でより成果を上げることに挑戦しています。",
        },
        {
          h3: "分割勤務",
          p: "いわゆる中抜けを可能にしており、午前は家でテレワーク、午後は会社に出社するなどの勤務も可能です。",
        },
        {
          h3: "WL（WorkLife）職",
          p: "社員自らの意思で週の出勤時間と、1日の勤務時間を選択することができます。介護や育児以外の理由でも、持病、勉強、副業など、理由は問いません。",
        },
      ],
    },
  ];
  function load_effect() {
    if (typeof window === "object") {
      var element = document.getElementsByClassName("load-fade");
      if (!element) return; // 要素がない場合は終了

      for (var i = 0; i < element.length; i++) {
        element[i].classList.add("is-show");
      }
    }
  }
  setTimeout(load_effect, 1000);
  return (
    <div>
      <Head>
        <title>KDDI Web Comunnications オフィス紹介サイト</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="base-color">
        <div>
          {data.map((items, index) => (
            <div key={index}>
              <div className="flex justify-items-center items-center mb-[180px]">
                <Image
                  src={items.img}
                  alt={""}
                  height={800}
                  width={900}
                  className="w-[80%] h-auto"
                  priority
                />
                <h2 className="load-fade writing-mode choice-font mx-auto max-md:text-xl">
                  {items.h2}
                </h2>
              </div>
              {items.text.map((items, index) => (
                <div key={index} className="w-[70%] mx-auto my-20">
                  <h3 className="sub-tittle mb-5">{items.h3}</h3>
                  <p>{items.p}</p>
                </div>
              ))}
            </div>
          ))}
        </div>
        <div className="pb-20">
          <Close url={"/"} />
        </div>
      </main>
    </div>
  );
}

export default time;
